### ISSUE TITLE
Delete output folder if already present and --overwrite-output is used, and improve error message if output is already present

### ISSUE THREAD

**Issue by johanneskoester** [datavzrd/datavzrd#329]
Instead of complaining that it already exists.

**Comment by fxwiegand** [comment]
Should we at least output a warning that it's gonna be deleted?

**Comment by johanneskoester** [comment]
You raise a valid point. Maybe refuse to overwrite (but with a better error message than now), and mention there that there is a flag --overwrite-output (and add that flag) to force overwriting it.

**Comment by fxwiegand** [comment]
Yeah that sounds good!
