### ISSUE TITLE
Tilde and equal in column names lead to errors

### ISSUE THREAD

**Issue by johanneskoester** [datavzrd/datavzrd#345]
Uncommon characters in column names like ~ or = lead to various errors when rendering the report. This should work fine of course. Sometimes, you don't even see an error but rather the displayed table is empty. One of the errors seems to be related with heatmaps and a lookup in `marks`. My suspicion is that sometimes the colnames are encoded into json without quoting them.

And just to anticipate other issues arising here: quotes in column names should be possible as well (although they are of course very unlikely). Maybe it is worth designinga testcase with lots of uncommon characters in various column names.

**Comment by dlaehnemann** [comment]
Just to document: This is the case for parentheses in column names, so `(` and/or `)`.

datavzrd throws no warning or error, but the report (with correct column names rendered) then simply displays:
```
No matching records found
```
