### ISSUE TITLE
Cargo.lock and Cargo.toml mismatch in release 2.18.0

### ISSUE THREAD

**Issue by yigitsever** [datavzrd/datavzrd#391]
Hello,

I maintain [datavzrd](https://aur.archlinux.org/packages/datavzrd) for Arch Linux User Repository (aur). We use the Cargo.lock file supplied by the upstream to create reproducible builds.

The 2.18.0 release has a mismatch between `Cargo.lock` and `Cargo.toml` for `minify-js` (and parse-js dependency) because #371 bumped the `minify-js` as usual but its version was pinned in #375 without updating `Cargo.lock`

**Comment by johanneskoester** [comment]
Thanks for reporting! Will be fixed with the next release! And great to see that datavzrd is in AUR already!

**Comment by fxwiegand** [comment]
@yigitsever we just released 2.18.1 with the fixed Cargo.lock file. Thanks again for pointing out the problem 😊
