### ISSUE TITLE
custom formatter for detail view card content

### ISSUE THREAD

**Issue by pecholleyn** [datavzrd/datavzrd#527]
By looking at the code I think that specifying `display-mode: detail` always put the data into generic Bootstrap Card, it would be nice if the `custom:` and `custom-path:` would also work with this mode to customize the Card body. In my case I would like to show some texts and table in the cards.

**Comment by fxwiegand** [comment]
Hey @pecholleyn!
Thanks for your suggestion! I just tackled this in #532 so you should be able to customize the content of any bootstrap cards in detail mode in the next release!
