### ISSUE TITLE
How to add pagination select?

### ISSUE THREAD

**Issue by ftabaro** [datavzrd/datavzrd#563]
Hello,

In the [compiled example](https://datavzrd.github.io/datavzrd/oscars/index_1.html), the table views show a nice pagination select (at the bottom). I cannot get it in my report and I cannot find the relevant options in the [example config file](https://github.com/datavzrd/datavzrd/blob/main/.examples/example-config.yaml). Can you guide me how to get this working?

**Comment by fxwiegand** [comment]
Hi!

Thanks for giving `datavzrd` a try! Would you mind sharing a bit more information about the dataset you are using and the specific problem you have? Especially the size of your dataset might give a hint about the missing pagination. Maybe take a look in our `README.md` file where all possible options and their defaults for the config are documented. `max-in-memory-rows` and `page-size` would probably be worth to take a look at.

**Comment by ftabaro** [comment]
I have four tables of different size, from ~1k to 32k lines. They are relatively narrow, with 8 or 9 columns depending if the table has row names or not. The `page-size` option works as expected, the table displays the given number of rows, I tried 25 and 10. I tried raising `max-in-memory-rows`, it restored the column header overview plot and filter for categorical variable but not the pagination.

**Comment by fxwiegand** [comment]
Ok so for these dimensions (more lines than given with `max-in-memory-rows` that defaults to `1000`) `datavzrd` stores table data across multiple html pages for performance reasons so you won't be able to get dynamic paging inside one html view without increasing `max-in-memory-rows`. You should still see a pagination at the bottom of each page that provides navigation between the different html pages.

**Comment by ftabaro** [comment]
Got it working by computing the number of rows of the largest table and passing it to `max-in-memory-rows`. It works. Thanks for your prompt and super efficient help :+1:

**Comment by fxwiegand** [comment]
> Got it working by computing the number of rows of the largest table and passing it to `max-in-memory-rows`. It works. Thanks for your prompt and super efficient help 👍

No problem at all! Happy to help! Hope you'll get some good use out of datavzrd!
