### ISSUE TITLE
improve error message or rendering upon empty input table

### ISSUE THREAD

**Issue by dlaehnemann** [datavzrd/datavzrd#582]
I have the case where sometimes an input table for datavzrd rendering ends up being empty (usually in minimal testing datasets). This currently leads to an error message like this one:

```
Error: Given argument mid-domain for domain for column "total perturbation accumulation" of view "spia_table" requires the dataset to only include numerical values in column "total perturbation accumulation".
```

From this, it is not clear that the actual problem is empty input. Would it be possible to implement either of the following two options:

1. Simply catch this case and improve the error message, saying that datavzrd cannot really do much with an empty input table.
2. Catch this and actually do what you can, which would be to render a table with only the heading and no rows.

I'd prefer option `2.`, as this would lead to consistent behavior / report creating in workflows, even when data doesn't produce any usable results for some of the analyses.

And please let me know if you need more specific details!

**Comment by fxwiegand** [comment]
Yes i absolutely agree on option two! The error handling needs to check if the dataset is empty and only throw the error you are getting when it is not.

Thanks for the catch! I'll be on it asap!
