### ISSUE TITLE
Feature request: Download filtered table

### ISSUE THREAD

**Issue by GitEnricoNeko** [datavzrd/datavzrd#637]
Hello together,

I'm using datavzrd 
and is really useful and well structured.
I was wondering if it's possible to include a download button, using the configuration file, for the final html allowing to download a user filtered table.
Thank in advance!

**Comment by fxwiegand** [comment]
Hi @GitEnricoNeko 

Thanks for using datavzrd! Would you want to download the raw data as csv data or are are you pointing to the plot export function (top right menu: show as plot)?

**Comment by GitEnricoNeko** [comment]
Hi @fxwiegand,
Basically, the idea is to open the HTML filter the table using the interactive filtering system that is super easy to integrate into the HTML table and then offer the possibility for the user to download the filtered table and not the original, raw, full table.
It's not clear for me if it's already possible.
Thanks for the support!

**Comment by fxwiegand** [comment]
I found some time to implement this today in #646. Maybe download the [example report generated in the CI](https://github.com/datavzrd/datavzrd/actions/runs/7711470609/artifacts/1205512314) and try it!
