### ISSUE TITLE
Feature request: Sort by column

### ISSUE THREAD

**Issue by stefanpeidli** [datavzrd/datavzrd#692]
Hi,
Awesome tool, thanks for developing it!

I would love to see an option to reorder columns in the html flexibly by a column. I have multiple numeric columns with thousands of rows, and in this case without sorting datavzrd becomes significantly less useful.

**Comment by fxwiegand** [comment]
Hi @stefanpeidli ,

Thanks for reaching out, and thanks for the kind words! We're glad you find datavzrd useful.

Regarding your suggestion to reorder columns in the HTML output flexibly, we understand the convenience this would provide, especially when dealing with large datasets. However, at the moment, we don't have plans to implement such a feature. The functionality would require a significant amount of work, and we're focused on other priorities for now.

As an alternative, we recommend using existing command-line tools to reorder columns beforehand. You might find [xsv](https://github.com/BurntSushi/xsv) or [csvkit](https://csvkit.readthedocs.io/) helpful for this purpose. These tools allow you to manipulate CSV data in various ways, including sorting, reordering, and more.

We appreciate your feedback and encourage you to keep suggesting features and improvements. If you have any other questions or need further assistance, please let us know.

**Comment by stefanpeidli** [comment]
Understandable, thanks for the explanation and the pointers!
